### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by narigondelsiglo** [matiasmagni/coreui-meteor-react#1]
Great work @matiasmagni !
I'm new to meteor and react, and I'm searching around the web for boilerplates as starting points...
Are you planning on moving the files from client to imports as the best practices say?
Thanks for sharing your work!

PS: soy argentino también!

**Comment by matiasmagni** [comment]
In the near future, I want to put it into atmospherejs.com as a meteor package. I have to figure out how to do that and I will!

I'm also specifying some kind of methodology in the building of SPAs, it's part of my thesis work. Could you help me filling the survey I made? Thanks!

SPANISH: https://matiasmagni.blogspot.com.ar/p/spa.html

ENGLISH: https://en-matiasmagni.blogspot.com.ar/p/spa.html

I also invite you to join my groups:
https://www.facebook.com/groups/spa.castellano/
https://www.facebook.com/SPA-Single-Page-Application-558321497832268/

PS: no había leído la posdata jajaja, genial, saludos!

**Comment by narigondelsiglo** [comment]
Ok! I'll be waiting for that package!
